### ISSUE TITLE
More precise bot check for msgCreate

### ISSUE THREAD

**Issue by Jgb14002** [WittyPleb/RuneCord#26]
As of now you have:
`if (msg.author.bot === true) return; // Do nothing if the message author is the bot.`

However this prevents any bot user from using RuneCord commands. It would nice to have this functionality. Perhaps you can check userIDs to make sure the message doesn't belong to the RuneCord bot rather than just checking if the author is a bot.

**Comment by WittyPleb** [comment]
It's a security measure that's in place, because other users could maliciously use it to create a bot and use a command over and over, creating overload on the bot.

I understand what you wish it to do, and I'm currently rewriting RuneCord to be better than ever, and I'll add a timer function for the various commands that work on resets and things (`~vos`, etc)

Sorry, but I'm not going to change it right now.
